### ISSUE TITLE
publish @mapbox/mvtview?

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/mvtview#3]
It seems that mvtview is not published on npm as `@mapbox/mvtview`.

**Comment by dbauszus-glx** [comment]
That's a shame. Just when I wanted to try npx.

**Comment by andrewharvey** [comment]
ping ping @mapsam not sure if you can help?

**Comment by andrewharvey** [comment]
As a workaround you can install it directly from GitHub.

**Comment by mapsam** [comment]
Yikes, sorry y'all! I accidentally published this as a private package (default for scoped packages). 

I just published v0.3.0 as public (and previous versions are now public as well)

https://www.npmjs.com/package/@mapbox/mvtview
