### ISSUE TITLE
can't get it working with gdal 2.3.0 output

### ISSUE THREAD

**Issue by max-mapper** [mapbox/mvtview#4]
hi, with gdal 2.3.0 i tried converting a geopdf to mvt like this:

`ogr2ogr -f MVT test.mvt test.pdf`

but running `mvtview` didn't work

```
 mvtview .
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at Object.<anonymous> (/Users/max/src/js/mvtview/cli.js:19:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
``` 

because i guess gdal uses the unpacked mvt folder format like this:

```
$ ls test.mvt
0  1  2  3  4  5  metadata.json
```

so then i tried gdal mbtiles (which is supposed to do mvt inside mbtiles now? i dunno) but that didnt work either

```
$ ogr2ogr -f MBTILES test.mbtiles test.pdf 
$ mvtview test.mbtiles 
Listening on http://localhost:3000
(node:49557) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unimplemented type: 3
(node:49557) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mapsam** [comment]
@maxogden a much belated response 👋 

> but running mvtview didn't work 
> mvtview .

The mvtview command requires a path to a file, but `.` is a directory path, hence the error `Error: EISDIR: illegal operation on a directory, read` when mvtview tries to read the entire directory. 

Try `mvtview tile.mvt`?

> so then i tried gdal mbtiles (which is supposed to do mvt inside mbtiles now? i dunno) but that didnt work either

mvtview doesn't work with MBTiles. You can try mbview though, which is essentially the same thing as this project, but specifically for the MBTiles format.
